//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1500
    {
        public long cod_sms { get; set; }
        public Nullable<decimal> nro_sms { get; set; }
        public string link_sms { get; set; }
        public string dir_sms { get; set; }
        public Nullable<long> ent_sms { get; set; }
        public string placa_ent { get; set; }
        public Nullable<System.DateTime> fecha_sms { get; set; }
        public string evento_sms { get; set; }
        public Nullable<decimal> vel_sms { get; set; }
    }
}
