//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1610
    {
        public decimal COD_EVENT { get; set; }
        public decimal COD_TEVENT { get; set; }
        public Nullable<System.DateTime> DATETIME_EVENT { get; set; }
        public decimal COD_ENT { get; set; }
        public Nullable<decimal> LAT_EVENT { get; set; }
        public Nullable<decimal> LON_EVENT { get; set; }
        public Nullable<decimal> CURSO_EVENT { get; set; }
        public Nullable<decimal> ALTITUD_EVENT { get; set; }
        public Nullable<decimal> PTA2_EVENT { get; set; }
        public Nullable<decimal> PTA1_EVENT { get; set; }
        public Nullable<decimal> MOTOR_EVENT { get; set; }
        public Nullable<decimal> ENCENDIDO_EVENT { get; set; }
    }
}
