//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1100
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAL_1100()
        {
            this.GAL_1310 = new HashSet<GAL_1310>();
        }
    
        public long COD_USU { get; set; }
        public string LOGIN_USU { get; set; }
        public string PASS_USU { get; set; }
        public string DES_USU { get; set; }
        public Nullable<decimal> COD_GUSU { get; set; }
        public string IP_USU { get; set; }
    
        public virtual GAL_1101 GAL_1101 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAL_1310> GAL_1310 { get; set; }
    }
}
