//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1680
    {
        public long cod_event { get; set; }
        public string evento { get; set; }
        public Nullable<System.DateTime> datetime_event { get; set; }
        public string entidad { get; set; }
        public Nullable<double> lat_event { get; set; }
        public Nullable<double> lon_event { get; set; }
        public string address_event { get; set; }
        public Nullable<int> calc_addr_event { get; set; }
        public string serial_ent { get; set; }
        public string INFOWINDOW_EVENT { get; set; }
        public Nullable<long> cod_ent { get; set; }
        public string Image { get; set; }
        public string Shadow { get; set; }
        public string Size { get; set; }
        public string anchor { get; set; }
        public string ShadowSize { get; set; }
        public Nullable<decimal> cmd_event { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
