//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1800
    {
        public decimal COD_COLOR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> R { get; set; }
        public Nullable<decimal> G { get; set; }
        public Nullable<decimal> B { get; set; }
    }
}
