//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1201
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAL_1201()
        {
            this.GAL_1300 = new HashSet<GAL_1300>();
        }
    
        public long COD_FLEET { get; set; }
        public string DES_FLEET { get; set; }
        public Nullable<decimal> STATUS_FLEET { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION_FLEET { get; set; }
        public Nullable<long> COD_CLIE { get; set; }
    
        public virtual GAL_1200 GAL_1200 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAL_1300> GAL_1300 { get; set; }
    }
}
