//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1000
    {
        public decimal COD_OWNER { get; set; }
        public string RIF_OWNER { get; set; }
        public string NIT_OWNER { get; set; }
        public string RS_OWNER { get; set; }
        public string TEL1_OWNER { get; set; }
        public string TEL2_OWNER { get; set; }
        public string FAX_OWNER { get; set; }
        public string CE_OWNER { get; set; }
        public string URL_OWNER { get; set; }
        public string D_IMP1_OWNER { get; set; }
        public Nullable<decimal> A_IMP1_OWNER { get; set; }
        public string D_IMP2_OWNER { get; set; }
        public Nullable<decimal> A_IMP2_OWNER { get; set; }
        public string D_IMP3_OWNER { get; set; }
        public Nullable<decimal> A_IMP3_OWNER { get; set; }
        public decimal lic_owner { get; set; }
    }
}
