//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1600
    {
        public long COD_EVENT { get; set; }
        public decimal COD_TEVENT { get; set; }
        public System.DateTime DATETIME_EVENT { get; set; }
        public long COD_ENT { get; set; }
        public decimal LAT_EVENT { get; set; }
        public decimal LON_EVENT { get; set; }
        public Nullable<decimal> CURSO_EVENT { get; set; }
        public Nullable<decimal> ALTITUD_EVENT { get; set; }
        public Nullable<decimal> PTA2_EVENT { get; set; }
        public Nullable<decimal> PTA1_EVENT { get; set; }
        public Nullable<decimal> MOTOR_EVENT { get; set; }
        public Nullable<decimal> ENCENDIDO_EVENT { get; set; }
        public string ADDRESS_EVENT { get; set; }
        public Nullable<decimal> VELOCITY_EVENT { get; set; }
        public Nullable<decimal> odometer_event { get; set; }
        public Nullable<decimal> calc_addr_event { get; set; }
        public string infowindow_event { get; set; }
        public string Anchor { get; set; }
        public string Image { get; set; }
        public string Shadow { get; set; }
        public string ShadowSize { get; set; }
        public string Size { get; set; }
    }
}
