//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1010
    {
        public long COD_APPL { get; set; }
        public string NOM_APPL { get; set; }
        public string DES_APPL { get; set; }
        public string IP_APPL { get; set; }
        public string TYPE_APPL { get; set; }
        public Nullable<long> COD_USU { get; set; }
        public Nullable<decimal> PORT_APPL { get; set; }
    }
}
