//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1900
    {
        public decimal COD_CMD { get; set; }
        public string des_cmd { get; set; }
        public string lit_cmd { get; set; }
        public Nullable<decimal> num_cmd { get; set; }
        public decimal cod_tcmd { get; set; }
        public Nullable<decimal> popup_cmd { get; set; }
    }
}
