//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1400
    {
        public decimal COD_MAP { get; set; }
        public string DES_MAP { get; set; }
        public string NOM_MAP { get; set; }
        public string FIELD1_MAP { get; set; }
        public string FIELD2_MAP { get; set; }
        public Nullable<decimal> ZOOM_MAP { get; set; }
        public string RUTA_MAP { get; set; }
        public Nullable<decimal> TIPO_MAP { get; set; }
        public Nullable<decimal> COLOR_MAP { get; set; }
        public Nullable<decimal> SYMBOL_MAP { get; set; }
        public string FONT_MAP { get; set; }
        public Nullable<decimal> VISIBLE_MAP { get; set; }
        public Nullable<decimal> size_map { get; set; }
        public Nullable<decimal> style_map { get; set; }
        public Nullable<decimal> outline_map { get; set; }
    }
}
