//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAL_1310
    {
        public long COD_USU_ENT { get; set; }
        public long cod_usu { get; set; }
        public long cod_ent { get; set; }
    
        public virtual GAL_1100 GAL_1100 { get; set; }
        public virtual GAL_1300 GAL_1300 { get; set; }
    }
}
