//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_galileo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class galileo_dbEntities : DbContext
    {
        public galileo_dbEntities()
            : base("name=galileo_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GAL_1100> GAL_1100 { get; set; }
        public virtual DbSet<GAL_1101> GAL_1101 { get; set; }
        public virtual DbSet<GAL_1102> GAL_1102 { get; set; }
        public virtual DbSet<GAL_1200> GAL_1200 { get; set; }
        public virtual DbSet<GAL_1201> GAL_1201 { get; set; }
        public virtual DbSet<GAL_1300> GAL_1300 { get; set; }
        public virtual DbSet<GAL_1302> GAL_1302 { get; set; }
        public virtual DbSet<GAL_1304> GAL_1304 { get; set; }
        public virtual DbSet<GAL_1310> GAL_1310 { get; set; }
        public virtual DbSet<GAL_1600> GAL_1600 { get; set; }
        public virtual DbSet<GAL_1680> GAL_1680 { get; set; }
        public virtual DbSet<GAL_1000> GAL_1000 { get; set; }
        public virtual DbSet<GAL_1001> GAL_1001 { get; set; }
        public virtual DbSet<GAL_1010> GAL_1010 { get; set; }
        public virtual DbSet<GAL_1301> GAL_1301 { get; set; }
        public virtual DbSet<GAL_1303> GAL_1303 { get; set; }
        public virtual DbSet<GAL_1320> GAL_1320 { get; set; }
        public virtual DbSet<GAL_1400> GAL_1400 { get; set; }
        public virtual DbSet<GAL_1500> GAL_1500 { get; set; }
        public virtual DbSet<GAL_1601> GAL_1601 { get; set; }
        public virtual DbSet<GAL_1610> GAL_1610 { get; set; }
        public virtual DbSet<GAL_1620> GAL_1620 { get; set; }
        public virtual DbSet<GAL_1800> GAL_1800 { get; set; }
        public virtual DbSet<GAL_1900> GAL_1900 { get; set; }
        public virtual DbSet<GAL_1910> GAL_1910 { get; set; }
        public virtual DbSet<GAL_8225> GAL_8225 { get; set; }
    }
}
